@startuml
	Class Hero {
		private posX : int
		private posY : int
		private jeu : Jeu

		public Hero()
		public deplacer(int x, int y) : void
		public subirDegat(int nbDegats) : void
		public getPosX() : int
		public getPosY() : int
        public setPosX(int posX) : void
        public setPosY(int posY) : void
	}
	Class Plateau {
        private plateau : boolean[][]
        public static HAUTEUR : int
        public static LARGEUR : int

        public Plateau()
        estLibre(int posX, int posY) : boolean
        appliquerEffetCase(int posX, int posY) : void
        affichageText() : void

	}
	Class Jeu <<Singleton>>{
	    private static instance : Jeu
        private fini : boolean
        private hero : Hero

        private Jeu()
        public static getInstance() : Jeu
        public isFinished() : boolean
        public getPlateau() : Plateau
        public getHero() : Hero
        public setHero(Hero hero) : void
        public setFini(boolean fini) : void
        public estMort() : void
        public appliquerDegat(int nbDegats) : void
	}

	Interface ICase {
	    public estTraversable() : boolean
	    public appliquerEffet() : void
	}

	Interface Objet <<Strategie>>{
	    public appliquerEffet() : void
	}

	Class CaseMur {
	    public estTraversable() : boolean
	    public appliquerEffet() : void
	}

	Class ObjetTresor {
	    public appliquerEffet() : void
	}

	Class Case {
	    public objet : Objet
	    public estTraversable() : boolean
	    public appliquerEffet() : void
	}

	Class ObjetPiege {
	    public appliquerEffet() : void
	}

    Objet <.. ObjetPiege
    ICase <.. Case
    ICase <.. CaseMur
    Objet <.. ObjetTresor
    Case -- "1" Objet
    Plateau -- "*" ICase
	Jeu "1" -down- "1" Hero
	Jeu -right- "1" Plateau
@enduml
