@startuml
	Class Hero {
		private posX : int
		private posY : int
		private plateau : Plateau

		public Hero()
		public deplacer(int x, int y) : void
		public getPosX() : int
		public getPosY() : int
        public setPosX(int posX) : void
        public setPosY(int posY) : void
	}
	Class Plateau {
        private plateau : boolean[][]
        public static HAUTEUR : int
        public static LARGEUR : int

        public Plateau()
        estLibre(int posX, int posY) : boolean
        appliquerEffetCase(int posX, int posY) : void
        affichageText() : void

	}
	Class Jeu {
	    private static instance : Jeu
        private fini : boolean
        private hero : Hero

        private Jeu()
        public static getInstance() : Jeu
        public isFinished() : boolean
        public getPlateau() : Plateau
        public getHero() : Hero
        public setHero(Hero hero) : void
	}

	Interface Case {
	    public estTraversable() : boolean
	    public appliquerEffet() : boolean
	}

	Class CaseMur {
	    public estTraversable() : boolean
	    public appliquerEffet() : boolean
	}

	Class CaseTresor {
	    public estTraversable() : boolean
	    public appliquerEffet() : boolean
	}

	Class CaseVide {
	    public estTraversable() : boolean
	    public appliquerEffet() : boolean
	}

    Case <.. CaseVide
    Case <.. CaseMur
    Case <.. CaseTresor
    Plateau -- "*" Case
	Jeu "1" -down- "1" Hero
	Jeu -right- "1" Plateau
@enduml
